config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users do
    collection do
      get :verification_screen
      put :verification
      get :resend_verification_code
    end
  end

  unauthenticated :user do
    root to: 'home#index'
  end

  authenticated :user do
    root to: 'home#dashboard', as: :user_dashboard
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable, :trackable

  validates :email, :password, :password_confirmation, presence: true
  validates :email, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_detail.rb
class BillingDetail < ApplicationRecord
  WHITELIST_ATTRIBUTE = %i[
    id
    phone
    payment_request_id
    user_id
    _destroy

  ].freeze

  belongs_to :payment_request
  belongs_to :user

  validates :phone, presence: true
end

app/models/payment_request.rb
class PaymentRequest < ApplicationRecord
  WHITELIST_ATTRIBUTE = [
    :title,
    :description,
    :bill_attachment,
    :bill_total,
    { billing_details_attributes: BillingDetail::WHITELIST_ATTRIBUTE }

  ].freeze

  attr_accessor :invalid_bill_attachment

  has_one_attached :bill_attachment

  has_many :billing_details, dependent: :destroy

  validates :title, presence: true

  validate :upload_valid_bill_with_total

  accepts_nested_attributes_for :billing_details, reject_if: ->(a) { a[:phone].blank? }, allow_destroy: true

  def upload_valid_bill_with_total
    return if invalid_bill_attachment.blank?
    errors.add(:base, "Please upload a valid clear image for bill or type total amount.")
  end

end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  before_validation :generate_identifier

  def generate_identifier
    return unless identifier.nil?

    new_identifier = ShortUrl.random_identifier

    self.identifier = if ShortUrl.find_by_identifier(new_identifier)
                        generate_identifier
                      else
                        new_identifier
                      end
  end

  class << self
    def random_identifier
      o = [('a'..'z'), ('0'..'9')].map { |i| i.to_a }.flatten.delete_if { |c| %w[o l 0 1].include?(c) }
      string = (0..4).map { o[rand(o.length)] }.join
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  validates :email, :password, :password_confirmation, :phone, presence: true
  validates :email, :phone, uniqueness: true

  after_create :send_verfivation_code

  has_many :billing_details, dependent: :destroy
  has_many :payment_requests, through: :billing_details

  def to_s
    "#{first_name} #{last_name}"
  end

  def send_verfivation_code
    generate_verification_code
    Twilio::SmsSender.new(self, "#{verification_code} is your verification code").send!
  end

  private

  def generate_verification_code
    begin
      code = SecureRandom.rand.to_s[2..5]
    end while User.where(verification_code: code).present?
    self.update_column(:verification_code, code)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def user_verified_authentication
    if current_user && !current_user.is_verified?
      return redirect_to verification_screen_users_path, alert: 'You are not verified user'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation phone])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :user_verified_authentication

  def index; end

  def dashboard; end
end

app/controllers/payment_requests_controller.rb
class PaymentRequestsController < ApplicationController
  before_action :user_verified_authentication
  before_action :load_payment_request, only: %i[show]

  def index
    @payment_request = current_user.payment_requests
  end

  def create
    @payment_request = PaymentRequest.new(payment_request_params)
    @payment_request = Bills::TotalReader.new(@payment_request).read
    #@payment_request.bill_total = 1000 #ToDO bill_total of payment request would be set as per the AWS texture reading. for now assigning 1000 hardcode
    if @payment_request.save
      Bills::Divider.new(@payment_request).call
      redirect_to(payment_requests_path, notice: 'Payment Request Created Successfully')
    else
      render :new
    end
  end

  def new
    @payment_request = PaymentRequest.new
    @payment_request.billing_details.new
  end

  def show;end

  private

  def load_payment_request
    @payment_request = PaymentRequest.find_by(id: params[:id])
  end

  def payment_request_params
    params.require(:payment_request).permit(*PaymentRequest::WHITELIST_ATTRIBUTE)
  end
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  skip_before_action :authenticate_user!

  def redirect
    @short_url = ShortUrl.find_by_identifier(params[:identifier])
    if @short_url
      redirect_to @short_url.long_url
    else
      flash[:error] = "The link you specified is invalid: #{request.original_url}"
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def verification_screen;  end

  def verification
    if current_user.verification_code == params[:verification_code]
      current_user.update_column(:is_verified, true)
      redirect_to root_path, notice: 'User verifified successfully'
    else
      redirect_to verification_screen_users_path, alert: 'Invalid verification code'
    end
  end

  def resend_verification_code
    current_user.send_verfivation_code
    redirect_to verification_screen_users_path, notice: 'Verification code has been sent'
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
  def home_page?
    controller_name == 'home' && action_name == 'index'
  end
end

app/views/home/_main_slider.html.haml
.container
  .row
    .col-sm-12.col-md-6
      %h1.home-title Lorem Ipsum is manage money simply dummy
      %h2.home-title Reach your goals with personalized insights,custom budgets, spend and subscription monitoring
      .buttons
        %a.btn.sign-up Download
        %a.btn.sign-in Read More
    .col-sm-12.col-md-6.phone-image
      = image_tag "phone.png", class: 'img-fluid phone', alt: 'phone'

app/views/home/dashboard.html.haml
.container
  %p.inner-title.buttons
    Lorem Ipsum is simply dummy text of the printing
  %p.inner-text
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
    dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
    book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
    unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
    recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
  .row.gx-5
    .p-3.col-sm-12.col-md-6
      =image_tag "male.png", class: 'img-fluid', alt: 'male'
    .p-3.col-sm-12.col-md-6
      %p.inner-title.text-position
        Lorem Ipsum is simply dummy text of the printing
      %p.inner-text.text-position
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type
        specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
        essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
        passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
    .p-3.col-sm-12.col-md-6
      %p.inner-title.text-position
        Lorem Ipsum is simply dummy text of the printing
      %p.inner-text.text-position
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type
        specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
        essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
        passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
    .p-3.col-sm-12.col-md-6
      =image_tag "female.png", class: 'img-fluid', alt: 'female'
  / Partners Section
  .container.partner-section
    .row
      .p-3.col-sm-12.col-lg-4
        %p.partners.title Best Partners
        %p.partner-title
          Fusce vulputate eleifend sapien bulum purus quam, scelerisque ut, mollis vulputate felis eros.
      .p-3.col-sm-6.col-lg-2.label-icon
        =image_tag "icon5.png", class: 'img-fluid', alt: 'icon5'
      .p-3.col-sm-6.col-lg-2.label-icon
        =image_tag "icon6.png", class: 'img-fluid', alt: 'icon6'
      .p-3.col-sm-6.col-lg-2.label-icon
        =image_tag "icon8.png", class: 'img-fluid', alt: 'icon8'
      .p-3.col-sm-6.col-lg-2.label-icon
        =image_tag "icon7.png", class: 'img-fluid', alt: 'icon7'

app/views/home/index.html.erb
<%= render 'payment_requests/list' %>

app/views/home/index.html.haml
/ Divided Section
.container
  .row.second-row
    .p-3.col-sm-12.col-md-4
      =image_tag "person1.png", class: 'img-fluid person1', alt: 'person1'
    .p-3.col-sm-12.col-md-1
    .p-3.col-sm-12.col-md-7
      %h1.title Lorem Ipsum Is
      %h3.subtitle
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
        when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    .p-3.col-sm-12.col-md-7
      %h1.title1
        Lorem Ipsum Is
      %h3.subtitle
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type
    .p-3.col-sm-12.col-md-1
    .p-3.col-sm-12.col-md-4
      =image_tag "person2.png", class: 'img-fluid person2', alt: 'person2'
/ Gallery Section
.container-fluid
  .row
    .col-sm-12.col-md-6.black-image
      %h1.home-title Lorem Ipsum Is
      %h4.home-title
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem  standard dummy text ever since the 1500s, when an unknown printer took
      =image_tag "phone1.png", class: 'img-fluid phone1', alt: 'phone1'
    .col-sm-12.col-md-6.blue-image
      %h1.home-title Lorem Ipsum Is
      %h4.home-title
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem  standard dummy text ever since the 1500s, when an unknown printer took
      =image_tag "phone2.png", class: 'img-fluid phone2', alt: 'phone2'   
/ Service Section
.container
  .row.icon-row
    .p-3.col-sm-12.col-md-6.col-lg-3
      =image_tag "icon1.png", class: 'img-fluid icon', alt: 'icon1'
      %h5.icon-title Out of the box ideas
      %h6.icon-subtitle Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus est nec enim egestas
    .p-3.col-sm-12.col-md-6.col-lg-3
      =image_tag "icon2.png", class: 'img-fluid icon', alt: 'icon2'
      %h5.icon-title Out of the box ideas
      %h6.icon-subtitle Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus est nec enim egestas
    .p-3.col-sm-12.col-md-6.col-lg-3
      =image_tag "icon3.png", class: 'img-fluid icon', alt: 'icon3'
      %h5.icon-title Fits all screens
      %h6.icon-subtitle Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus est nec enim egestas
    .p-3.col-sm-12.col-md-6.col-lg-3
      =image_tag "icon4.png", class: 'img-fluid icon', alt: 'icon4'
      %h5.icon-title 24/7 support
      %h6.icon-subtitle Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dapibus est nec enim egestas adipiscing. Nunc
/ Slider Section
#carouselExampleCaptions.carousel.slide{"data-bs-ride" => "carousel"}
  .carousel-indicators
    %button{"aria-label" => "Slide 1", "data-bs-slide-to" => "0", "data-bs-target" => "#carouselExampleCaptions", :type => "button"}
    %button.active{"aria-current" => "true", "aria-label" => "Slide 2", "data-bs-slide-to" => "1", "data-bs-target" => "#carouselExampleCaptions", :type => "button"}
    %button{"aria-label" => "Slide 3", "data-bs-slide-to" => "2", "data-bs-target" => "#carouselExampleCaptions", :type => "button"}
  .carousel-inner
    .carousel-item
      = image_tag 'green-background.png', class: 'd-block w-100', alt: ''
      .carousel-caption.d-md-block
        =image_tag "avatar.png", class: 'img-fluid avatar', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        %p.name Mark Steele
        %p.role Designer at LA STUDIO
        = image_tag 'line.png', class: 'img-fluid line', alt: 'line'
        %h3.description
          “Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
          officia deserunt mollit.”
    .carousel-item.active
      = image_tag 'green-background.png', class: 'd-block w-100', alt: ''
      .carousel-caption.d-md-block
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        %p.name Mark Steele
        %p.role Designer at LA STUDIO
        = image_tag 'line.png', class: 'img-fluid line', alt: 'line'
        %h3.description
          “Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
          officia deserunt mollit.”
    .carousel-item
      = image_tag 'green-background.png', class: 'd-block w-100', alt: ''
      .carousel-caption.d-md-block
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar1', alt: 'avatar'
        =image_tag "avatar.png", class: 'img-fluid avatar', alt: 'avatar'
        %p.name Mark Steele
        %p.role Designer at LA STUDIO
        = image_tag 'line.png', class: 'img-fluid line', alt: 'line'
        %h3.description
          “Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui
          officia deserunt mollit.”

.light-blue
  .container
    .row
      .col-sm-12.col-md-6.manage-money
        %h1.title Lorem Ipsum is
        %h1.title1 Manage money simply dummy
        %h3
          Reach your goals with personalized insights,custom budgets, spend tracking, and subscription monitoring all for free.
        %a.btn.sign-up.buttons download
      .col-sm-12.col-md-6
        =image_tag "iphone.png", class: 'img-fluid iphone', alt: 'iphone'
/ Partners Section
.container.partner-section
  .row
    .p-3.col-sm-12.col-lg-4
      %p.partners.title Best Partners
      %p.partner-title
        Fusce vulputate eleifend sapien bulum purus quam, scelerisque ut, mollis vulputate felis eros.
    .p-3.col-sm-6.col-lg-2.label-icon
      =image_tag "icon5.png", class: 'img-fluid', alt: 'icon5'
    .p-3.col-sm-6.col-lg-2.label-icon
      =image_tag "icon6.png", class: 'img-fluid', alt: 'icon6'
    .p-3.col-sm-6.col-lg-2.label-icon
      =image_tag "icon8.png", class: 'img-fluid', alt: 'icon8'
    .p-3.col-sm-6.col-lg-2.label-icon
      =image_tag "icon7.png", class: 'img-fluid', alt: 'icon7'

app/views/layouts/_footer.html.haml
/ Footer Section
.footer
  .container
    .row
      .p-3.col-xs-12.col-md-4
        %p.number 01.
        %p.footer-title about us
        =image_tag "logo1.png", class: 'img-fluid footer-logo', alt: 'footer-logo'
        .row
          .p-3.col-sm-12.col-lg-6
            .footer-bottom
              .icon-groups
                =image_tag "home.png", alt: 'home'
              .footer-icon-next
                %p.footer-text 900 Colonial Drive Woodbridge, VA 22191
          .p-3.col-sm-12.col-lg-6
            .footer-bottom
              .icon-groups
                =image_tag "tele.png", class: 'tele', alt: 'phone-email'
              .footer-icon-next
                %p.footer-text
                  %a{:href => "tel: +8 800 123 456 789"} +8 800 123 456 789
            .footer-bottom
              .icon-groups
                =image_tag "mail.png", class: 'mail', alt: 'phone-email'
              .footer-icon-next
                %p.footer-text
                  %a{:href => "mailto:admin@fwd.com"} admin@fwd.com
      .p-3.col-xs-12.col-md-4
        %p.number 02.
        %p.footer-title.footer-height our twitter
        .footer-bottom
          .icon-groups
            =image_tag "twitter.png", alt: 'twitter'
          .footer-icon-next
            %p.footer-text
              2,000 Sales Reached, Thanks for everyone!
              %a{:href => "https://t.co/aJSddQh2tT"} https://t.co/aJSddQh2tT
              %br/
              %span.title 20 days ago
        .footer-bottom
          .icon-groups
            =image_tag "twitter.png", alt: 'twitter'
          .footer-icon-next
            %p.footer-text
              Check out our new themes and templates
              %a{:href => "https://t.co/UHoAYEDb6c"} https://t.co/UHoAYEDb6c
              %br/
              %span.title 24 days ago
      .p-3.col-xs-12.col-md-4
        %p.number 03.
        %p.footer-title.footer-height subscribe now
        .input-group.mb-3
          %input.form-control{"aria-describedby" => "button-addon2", "aria-label" => "Email Address", :placeholder => "Email Address", :type => "text"}/
          %button#button-addon2.btn.btn-success{:type => "button"} SUBSCRIBE
        %p.footer-text
          Fusce vulputate eleifend sapien. Vestibulum purus uam, scelerisque ut, mollis sed, nonummy id, metus cumsan. lorem in dui. Cras ultricies mi eu turpis hendrerit.
.footer1
  .container
    %p.footer1-text @2021 All rights reserved

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light{class: ("nav-home" if current_user || !home_page?)}
  .container
    %a.navbar-brand{:href => "#"}
      - image_path = (current_user || !home_page?) ? 'logo2.png' : 'logo.png'
      = link_to root_path do
        = image_tag image_path, class: 'img-fluid logo', alt: 'Logo'
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse{class: ("nav-height" if current_user || !home_page?)}
      %ul.navbar-nav.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} How it works
        %li.nav-item
          %a.nav-link{:href => "#"} Credit Cards
        %li.nav-item
          %a.nav-link{:href => "#"} Investing
        %li.nav-item
          %a.nav-link{:href => "#"} Loans
        %li.nav-item
          %a.nav-link{:href => "#"} Resources
        %li.nav-item
          %a.nav-link{:href => "#"} Blog
        - unless current_user
          %li.nav-item
            = link_to 'Sign Up', new_user_registration_path, class: 'btn sign-up'
          %li.nav-item
            = link_to 'Sign In', new_user_session_path, class: 'btn sign-in'
        - else
          %li.nav-item
            = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn sign-out'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Bootstrap CSS
    %link{:href => "https://fonts.googleapis.com/css?family=Poppins", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,600,300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat:100,200,300", :rel => "stylesheet"}/
    %title PayTheTab
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %script{:crossorigin => "anonymous", :integrity => "sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"}
    / - Navbar
    .home
      = render 'layouts/header'
      - if home_page?
        = render 'home/main_slider'
    = yield
    / Footer Section
    = render 'layouts/footer'

app/views/layouts/shared/_standard_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger">
	  <a class="close" data-dismiss="alert">×</a>
	  <% obj.errors.full_messages.each do |msg| %>
	    <p><%= raw msg.to_s %></p>
	  <% end %>
	</div>
<% end %>

app/views/payment_requests/_billing_detail_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <label>Phone</label>
    <div class="input-group">
      <%= f.text_field :phone, class: "form-control" %>
      <% if f.object.new_record? %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      <% end %>
    </div>
  </div>
  <%= link_to_remove_association "<i class='fa fa-trash'></i>".html_safe, f , class: "btn btn-default" %>
</div>

app/views/payment_requests/_form.html.erb
<div class="container">
  <h2>Payment Request</h2>
  <%= form_for(@payment_request, :url => @payment_request.new_record? ? payment_requests_path : payment_request_path(@payment_request) ) do |f| %>
    <%= render partial: "layouts/shared/standard_errors", locals: {obj: @payment_request}%>
    <div class="form-group">
      <label for="email">Title:</label>
      <%= f.text_field :title , class: "form-control", placeholder: "title", required: true %>
    </div>
    <div class="form-group">
      <label for="pwd">Description:</label>
      <%= f.text_area :description , class: "form-control", placeholder: "Tell more about payment(optional)" %>
    </div>

    <div class="form-group">
      <label for="pwd">Bill Attachment:</label>
      <%= f.file_field :bill_attachment , class: "form-control" %>
      <span>Upload a valid clear image for bill or type total amount:</span>
    </div>

    <div class="form-group">
      <label for="pwd">Bill Total Amount</label>
      <%= f.text_field :bill_total , class: "form-control", placeholder: "Upload a valid clear image for bill or type total amount" %>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default" data-collapsed="0">
        
          <a data-toggle="collapse" data-target="#billing_detail">
            <div class="panel-heading">
              <div class="panel-title">
                <span class="account_new_header">Recipients</span>
              </div>
              <div class="panel-options">
                <a href="#" data-rel="collapse"><i class="entypo-down-open"></i></a>
              </div>
            </div>
          </a>

          <div id="billing_detail" class="collapse">
            <div class="panel-body">
              <div class="row">
                <div class="col-md-12">
                  <div class="col-md-6">
                    <%= f.fields_for :billing_details do |billing_detail_form| %>
                      <%= render 'billing_detail_fields', f: billing_detail_form %>
                    <% end %>
                    <div class="slinks">
                      <%= link_to_add_association 'Add More Recipient', f, :billing_details , class: "btn btn-default" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>

    <%= f.submit "Submit", class: 'btn btn-default' %>
  <% end %>
</div>

app/views/payment_requests/_list.html.erb
<div class="container">
  <h2>Payment Requests</h2>           
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Bill Total</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @payment_request.each do |payment_request| %>
        <tr>
          <td><%= payment_request.title %></td>
          <td><%= payment_request.bill_total %></td>
          <td><%= link_to "Show", payment_request_path(payment_request.id), method: :get, class: 'btn btn-default' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <%= link_to "Payment Request", new_payment_request_path, method: :get, class: 'btn btn-default' %>
  <br>
  <br>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
</div>

app/views/payment_requests/index.html.erb
<%= render 'list' %>

app/views/payment_requests/new.html.erb
<%= render 'form' %>

app/views/payment_requests/show.html.erb
<div class="container">
  <h2>Payment Request</h2>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="portlet-body">
        <div class="table-scrollable">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> Title </th>
                <td> <%= @payment_request.title %> </td>
              </tr>

              <tr>
                <th> Description </th>
                <td> <%= @payment_request.description %> </td>
              </tr>
              <% number = 1 %>
              <% @payment_request.billing_details.each do |detail| %>
              <tr>
                <th> Recipient #<%= number %> </th>
                <td></td>
              </tr>
              <tr>
                <th> Phone </th>
                <td>  <%= detail.phone %>  </td>
              </tr>
              <tr>
                <th> Per Head </th>
                <td>  <%= detail.per_head %>  </td>
              </tr>
              <% number = number + 1 %>
              <% end %>

            </thead>
          <tbody>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Payment Request", payment_requests_path, method: :get, class: 'btn btn-default' %>
  
</div>

app/views/users/verification_screen.html.haml
- user_name = current_user.to_s.present? ? current_user.to_s : "Sir"
.container
  .row.second-row
    %h2
      Hello #{user_name}, Please enter your verification code
    = form_with url: verification_users_path, method: :put do |form|
      = form.label :verification_code, "Verification Code"
      = form.text_field :verification_code
      = form.submit "Submit"
    %br/
    = link_to "Resend", resend_verification_code_users_path